apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashJS-deployment
  # labels:
  #   app: tiangolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashjs-app
  template:
    metadata:
      labels:
        app: dashjs-app
    spec:
      containers:
      - name: dashjs-app
        image: asture123/dashjs
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dashjs-app-service
spec:
  selector:
    app: dashjs-app
  ports:
    - protocol: TCP
      port: 1936
      targetPort: 3000
      # nodePort: 30001
  # type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashjs-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dashjs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashjs-app-service
            port:
              number: 1936
