apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-ls-deployment
spec:
  replicas: 3  # Ensure that there are as many replicas as you have nodes
  selector:
    matchLabels:
      app: dash-ls-app
  template:
    metadata:
      labels:
        app: dash-ls-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname 
          # topologyKey: zone #implies the even distribution will only be applied to nodes that are labeled zone: <any value>
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: dash-ls-app
      containers:
      - name: dash-ls-app
        image: alqutami/rtmp-hls
        ports:
        - containerPort: 1935  # RTMP port
        - containerPort: 8080  # HTTP (HLS) port
---
apiVersion: v1
kind: Service
metadata:
  name: dash-ls-app-service
spec:
  selector:
    app: dash-ls-app
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
      name: rtmp
      nodePort: 30001
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: stream
      nodePort: 30002
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash-ls-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dashlivestream.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dash-ls-app-service
            port:
              number: 8080    
            