apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-ls-deployment
  # labels:
  #   app: tiangolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dash-ls-app
  template:
    metadata:
      labels:
        app: dash-ls-app
    spec:
      nodeSelector:
        nodename: worker3
      containers:
      - name: dash-ls-app
        image: alqutami/rtmp-hls
        ports:
        - containerPort: 1935
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
        - mountPath: /var/lib/lsnginx/nginx.conf # docker run -v custom.conf:/etc/nginx/nginx.conf alqutami/rtmp-hls
        - subPath: custom.conf
      volumes:
      - name: nginx-config
        hostPath:
          path: /pv/lsnginx/nginx_custom.conf
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: dash-ls-app-service
spec:
  selector:
    app: dash-ls-app
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
      name: rtmp
      nodePort: 30001
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: stream
      nodePort: 30002
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash-ls-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dashlivestream.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dash-ls-app-service
            port:
              number: 8080    
            
